server: 
  port: 8080

database:
  user: yodamariadb
  password: root
  protocol: unix
  path: /run/mysqld/mysqld.sock
  dbname: sireng

jwt:
  secret: "belicikibelikoyosukiyokobokanaeruloveucintaku"
