host: localhost:8080
info:
  contact:
    email: mash1o1o1o1@gmail.com
    name: chaaaeeee
  description: Sinau bareng, a program that tracks user's study hours and share it
    with their friends! with Sireng, learning thins will be a lot more fun!
  title: Sireng API Documentation
  version: "0.7"
paths: {}
swagger: "2.0"
