host: localhost:8080
info:
  contact:
    email: mash1o1o1o1@gmail.com
    name: chaaaeeee
  description: Sireng is a badass API service that is designed for people who's lost
    in life, can't do shit by himself and having a hard time focusing. Sireng tracks
    your learning process and turns it into informative graphs for you to use it as
    a means of review. Sireng has a chat feature that you can use to ask for feedback
    from your friends or you can simply use it to wake your friend up and tell em
    to lock tf in.
  title: Sireng API Documentation
  version: "0.7"
paths: {}
swagger: "2.0"
